# ==========================================
# 1. Configuración de PostgreSQL (JPA)
# ==========================================
# Configuración de la Base de Datos con Muescas de Seguridad
spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:MiHorario}}}
spring.datasource.username=${DB_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${DB_PASSWORD:${PGPASSWORD:1234}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para actualizar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 2. Configuración de Redis (Caché Distribuida)
# ==========================================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:${REDISHOST:localhost}}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:${REDISPORT:6379}}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:${REDISPASSWORD:}}

# 3. Puerto del Servidor
server.port=${PORT:8081}

#4. Configuracion del Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


# ==========================================
# 5. Configuración del Punto 20: I18N (Internacionalización)
# ==========================================
# Especifica que el archivo base de traducciones está en src/main/resources/messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8
# Si viene un idioma que no tenemos (ej. Francés), usa por defecto el Español (messages.properties)
spring.messages.fallback-to-system-locale=true

# ==========================================
# 6. Credenciales del Servicio Externo (SendGrid)
# ==========================================
# Busca la variable de entorno del sistema, si no, usa una vacía por defecto

sendgrid.api.key=${SENDGRID_API_KEY:}
sendgrid.from.email=${SENDGRID_FROM_EMAIL:}

# ========================================
# 7. Configuración de Seguridad - Keycloak OIDC
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8090/realms/mihorario-realm}
KEYCLOAK_CLIENT_ID=mihorario-client
KEYCLOAK_CLIENT_SECRET=mo7YS1rDZOsylF4KVPQvDXr3ZorG5glP
template.shift.assigned.subject=Shift Assigned Notification
template.shift.assigned.body=Hello %s, you have been assigned to zone %s starting at %s.

# 8. Configuración de Spring Boot Actuator (Monitoreo)
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

