name: Java CI/CD con SonarCloud

on:
  push:
    branches: [ "main", "daniel-rama" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    name: Compilar y Analizar Código
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código del Repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Crucial para que Sonar lea el historial de Git correctamente

    - name: Configurar Java 21/25
      uses: actions/setup-java@v4
      with:
        java-version: '21' # O la versión exacta de JDK que manejes
        distribution: 'temurin'
        cache: maven

    - name: Cachear paquetes de SonarCloud
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cachear paquetes de Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Compilar y Lanzar Escaneo de Sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Lo genera GitHub solo
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        DB_URL: jdbc:postgresql://localhost:5432/MiHorario  # O la URL de tu BD de pruebas si usas una externa
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}    # Este lo guardaremos en GitHub ahora
      run: |
        mvn -B verify sonar:sonar \
          -Dsonar.projectKey=juandaniel08_MiHorarioApp \
          -Dsonar.organization=juandaniel08 \
          -Dsonar.host.url=https://sonarcloud.io